# Álgebra Linear com Python e Numpy
![Numpy](logonumpy.jpg)  
NumPy é um pacote para linguagem Python que nos possibilita realizar diversas operação com vetores e matrizes de forma rápida e eficiente. Neste notebook iremos apresentar brevemente alguns conceitos de Álgebra Linear e implementá-los com auxílio do pacote NumPy.  

# Conceitos Básicos de Álgebra Linear

## Escalares
Os escalares são variáveis que aceitam apenas um valor específico, esse valor pode ser um número inteiro, real, natural  ou complexo.

In [4]:
T = 37 #escalar que representa a tempetarura em graus Celsius
Vel = 80 #escalar que representa a velocidade instantânea em m/s
c = 150.00 #escalar que representa um valor monetário em R$

## Vetores
Os vetores podem ser vistos como uma coleção de escalares, utilizados para representar dimensões mais elevadas.

In [5]:
import numpy as np

In [6]:
VT = np.array([27, 37]) #vetor com duas dimensões
VV = np.array([20, 15, 100]) #vetor com três dimensões
VM = np.array([100, 205, 777, 111]) #vetor com quatro dimensões
type(VM)

numpy.ndarray

## Matrizes
As matrizes nos permitem representar uma coleção de vetores. Os elementos das matrizes podem ser números reais, complexos, expressões algébricas ou funções.
Chamamos de **diagonal principal** os elementos onde **i=m**.


![Representação Matriz](matriz.png)

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(A)

numpy.ndarray

Outra forma de representar uma matriz seria através do método **np.matrix()**

In [9]:
B = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
type(B)

numpy.matrixlib.defmatrix.matrix

In [11]:
A = np.matrix(A) #transformando o vetor multidimensional em matrix
type(A)

numpy.matrixlib.defmatrix.matrix

### Matriz quadrada
Uma matriz é considerada quadrada como número de linhas for igual ao número de columas, ou seja, **m=n**.


### Matriz diagonal
Uma matriz quadrada é considerada diagonal quando todos os elementos fora da diagonal principal forem nulos, ou seja, **ij = 0 para todo i!=j**.  
Podemos escrever uma matriz diagonal em python utilizando o método **diag()**.

In [12]:
np.diag([1, 5, 7, 9, 10, 1])

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  1]])

### Matriz triangular


Uma matriz é considerada **triangular superior** se amn = 0 quando m > n, ou seja, quandos os elementos abaixo da diagonal principal forem iguais a zero.
![Matriz Superior](matrizsuperior.jpg)

Uma matriz é considerada **triangular inferior** se amn = 0 quando m < n, ou seja, quandos os elementos acima da diagonal principal forem iguais a zero.
![Matriz Inferior](matrizinferior.jpg)

### Matriz linha
Podemos representar uma matriz linha por:

In [13]:
B = np.array([[2, 4, 6,-10]]) #utilizando um conjunto a mais de colchetes ou parênteses
B

array([[  2,   4,   6, -10]])

### Matriz coluna
Podemos representar uma matriz coluna por:

In [14]:
D = np.array([[2],[-4],[6],[-10]])
D

array([[  2],
       [ -4],
       [  6],
       [-10]])

Poderíamos ter obtido a matriz coluna D obtendo a transposta da matriz linha B.

In [15]:
Dt = np.transpose(B)
Dt

array([[  2],
       [  4],
       [  6],
       [-10]])

### Matriz nula
Uma matriz é considerada nula se e somente se todos os seus elementos forem iguais a zero. Podemos definir uma matriz nula em python utilizando a função **np.zeros** passando a dimensão que desejamos.

In [16]:
N = np.zeros([2,2])
N

array([[0., 0.],
       [0., 0.]])

### Matriz identidade 
Uma matriz identidade é aquela na qual a diagonal principal possui todos os valores iguais a 1 e os demais valores iguais a zero. A matriz identidade é muito utilizada na resolução de sistemas de equações lineares. No python podemos representar uma matriz identidade através da função **np.identity()** passando como argumento a dimensão desejada.

In [17]:
MI = np.identity(4)
MI

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Matriz transposta
A **matriz transposta** é uma matriz obtida através da troca ordenada de linhas por colunas de uma dada matriz, essa operação pode ser realizada utilizando a função **np.transpose**. A transposição não altera a diagonal principal de uma matriz quadrada.


### Propriedades:
![Propriedades Transposta](propriedadestransposta.jpg)



In [18]:
A = np.array([[1,0,3],[2,1,4]])
A

array([[1, 0, 3],
       [2, 1, 4]])

In [19]:
At = np.transpose(A)
At

array([[1, 2],
       [0, 1],
       [3, 4]])

A matriz transposta também pode ser obtidade através do método **.T**.

In [20]:
At = A.T
At

array([[1, 2],
       [0, 1],
       [3, 4]])

Vamos verificar a validação de cada uma das propriedades:

In [21]:
A = np.array(([1,2],[3,4]))
B = np.array(([5,6],[7,8]))
A == B

array([[False, False],
       [False, False]])

In [22]:
#Propriedade 1
(A.T).T == A

array([[ True,  True],
       [ True,  True]])

In [23]:
#Propriedade 2
(A+B).T == A.T + B.T

array([[ True,  True],
       [ True,  True]])

In [24]:
#Propriedade 3
(7*A).T == 7*A.T

array([[ True,  True],
       [ True,  True]])

In [25]:
#Propriedade 4
(A*B).T == B.T*A.T

array([[ True,  True],
       [ True,  True]])

## Operações

### Operações com vetores e escalares

In [26]:
v1 = np.array([1, 2, 3, 4, 5])
v1

array([1, 2, 3, 4, 5])

In [27]:
r1 = v1 + 2 #adiciona o escalar 2 a cada elemento do vetor
r1

array([3, 4, 5, 6, 7])

In [28]:
r2 = (v1*3)/10
r2

array([0.3, 0.6, 0.9, 1.2, 1.5])

### Operações entre vetores

In [29]:
v1 = np.array([1,2,3,4,5]) #vetor linha
v2 = np.array([2,3,5,1,4])

In [30]:
v3 = v1 * v2
v3

array([ 2,  6, 15,  4, 20])

In [31]:
v4 = v1 + v2 - 3*v1
v4

array([ 0, -1, -1, -7, -6])

### Operações entre matrizes e escalares

In [32]:
A = np.array(([1,1,1],[2,2,2],[3,3,3]))
A

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [33]:
2*A

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [34]:
A-2*10

array([[-19, -19, -19],
       [-18, -18, -18],
       [-17, -17, -17]])

### Operações entre matrizes e vetores  
Na **multiplicação** de um vetor por uma matriz, precisamos **verificar se as dimensões são compatíveis**, ou seja, se o número de colunas são iguais. 

In [35]:
L = np.array([1,2])
A = np.array([1,2,3]) #vetor
B = np.array(([1,1,1],[2,2,2]))

In [36]:
C = A*B
C

array([[1, 2, 3],
       [2, 4, 6]])

In [37]:
#F = L*A #exemplo de operação não compatível 

In [38]:
B = np.array(([1,1,1],[2,2,2]))
A = np.array([1,2,3])

In [39]:
G = B - A
G

array([[ 0, -1, -2],
       [ 1,  0, -1]])

In [40]:
GI = A - B
GI

array([[ 0,  1,  2],
       [-1,  0,  1]])

In [41]:
D = A/B
D

array([[1. , 2. , 3. ],
       [0.5, 1. , 1.5]])

### Operações entre matrizes
Precisamos conferir se as dimensões são compatíveis para efetuar as operações matemáticas.

In [42]:
A = np.array(([1,1],[2,2]))
B = np.array(([20,20],[40,40]))
C = np.array(([1,2,3],[4,5,6]))

In [43]:
S = A + B
S

array([[21, 21],
       [42, 42]])

In [44]:
D = A/B
D

array([[0.05, 0.05],
       [0.05, 0.05]])

In [45]:
M = A*B #multiplicação entre os elementos das matrizes e não o produto entre elas
M

array([[20, 20],
       [80, 80]])

A multiplicação entre os elementos das matrizes pode ser realizada através da função **np.multiply()**.

In [46]:
M = np.multiply(A,B)
M

array([[20, 20],
       [80, 80]])

**Obs:** Só podemos realizar o produto entre duas matrizes se o número de colunas da primeira matriz for igual ao número de linhas da segunda. O produto entre matrizes pode ser feito através do método **np.dot(m1,m2)**.

![Produto entre matrizes](produtomatrizes.jpg)

No produto entre matrizes, cada elemento da linha da primeira coluna deve ser multiplicado e somado pelos correspondentes elementos da coluna da segunda matriz.

In [47]:
A = np.array(([2,1],[5,3],[4,2]))
B = np.array(([3,1,0],[4,2,1]))
R1 = np.dot(A,B)
R1

array([[10,  4,  1],
       [27, 11,  3],
       [20,  8,  2]])

Não temos comutatividade no produto entre matrizes, a ordem importa!

In [48]:
R2 = np.dot(B,A)
R2

array([[11,  6],
       [22, 12]])

In [49]:
M1 = np.array([[1,2,3,4]])
M2 = np.array([[20,30,40,50]])
M3 = M1*M2
M3

array([[ 20,  60, 120, 200]])

Como o número de colunas de M1 é diferente do número de linhas de M2, o produto não é possível. Entretanto, podemos efetuar a operação obtendo a transposta de M1.

In [50]:
M4 = np.dot(np.transpose(M1),M2)
M4

array([[ 20,  30,  40,  50],
       [ 40,  60,  80, 100],
       [ 60,  90, 120, 150],
       [ 80, 120, 160, 200]])

### Traço da matriz  
O traço de uma matriz quadrada é a soma dos elementos da sua diagonal principal, o traço pode ser obtido através da função **np.trace()**.

In [51]:
A = np.array(([1,2],[2,2]))
np.trace(A)

3

No caso de uma matriz não quadrada, a soma será da parte da diagonal principal referente a uma matriz quadrada, exemplo:

![Traço matriz não quadrada](traçomatriz.jpg)

In [52]:
B = np.array(([1,1,1],[3,3,3]))
np.trace(B)

4

### Propriedades Traço

1. tr(A+B) = tr(A) + tr(B)
2. tr(λ*A) = λ * tr(A)
3. O traço de uma matriz quadrada é igual ao traço de sua transposta.
4. tr(AB) = tr(BA) o traço de um produto de matrizes quadradas não dependem da ordem do produto.
5. O traço de uma matriz simétrica é igual a soma dos seus valores próprios (autovalores). Uma matriz A é dita simétrica se ela for igual a sua transposta.

In [53]:
A = np.array(([1,1],[2,2]))
B = np.array(([3,3],[4,4]))

In [54]:
#Propriedade 1
np.trace(A+B) ==  np.trace(A) + np.trace(B)

True

In [55]:
#Propriedade 2
np.trace(5*A) == 5 * np.trace(A)

True

In [56]:
#Propriedade 3
np.trace(A) == np.trace(np.transpose(A))

True

In [57]:
#Propriedade 4
np.trace(A*B) == np.trace(B*A)

True

### Inversa de uma matriz  
Se o produto de duas matrizes resulta em uma matriz identidade, essa matriz possui uma inversa. A biblioteca Numpy possuí um pacote específico para trabalhar com álgebra linear, se chama **numpy.lialg**, no qual possuí a função **inv()** para calcular a inversa de uma matriz.

In [58]:
from numpy.linalg import inv

In [59]:
A = np.array(([1,2],[3,4]))
A

array([[1, 2],
       [3, 4]])

In [60]:
B = inv(A)
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Para verificar se a matriz B é inversa da matriz A:

In [61]:
np.dot(B,A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

### Propriedades da matriz inversa:  
1. Se A for uma matriz inversa, a inversa de A também será invertível
![Propriedade 1](propriedade1.jpg)

In [62]:
A = np.array(([1.,2.],[3.,4.]))
inv(inv(A)) == A #o retorno é falso por motivos de arredondamento

array([[False, False],
       [False, False]])

2. Se A e B forem matrizes invertíveis, então AB também é invertível
![Propriedade 2](propriedade2.jpg)

In [63]:
A

array([[1., 2.],
       [3., 4.]])

In [64]:
B = inv(A)
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [65]:
inv(A.dot(B))

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [66]:
inv(B).dot(inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

3. Se A é uma matriz invertível, então a seguinte propriedade é válida:
![Propriedade 3](propriedade3.jpg)

In [67]:
inv(A.T)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [68]:
(inv(A)).T

array([[-2. ,  1.5],
       [ 1. , -0.5]])

### Manipulando elementos da matriz

In [69]:
A = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

A referência para linhas e colunas começa a partir do número zero

In [70]:
a11 = A[0,0]
a11

1

In [71]:
#Retornando a primeira linha
A1n = A[0,:]
A1n

array([1, 2, 3, 4])

In [72]:
#Retornando a segunda coluna
Am2 = A[:,1]
Am2

array([ 2,  6, 10])

# Sistemas de Equações Lineares  
Sistemas lineares é um conjunto de duas ou mais equações lineares. Sua forma é dada por:  
![Sistemas Lineares](sistemaslineares.jpg)  
Onde os termos acima:
* **x1, x2,..., xn** são **incógnitas do sistema**  
* **a11, a22,..., amn** são as **variáveis dependentes**
* **b1, b2,..., bm** são os **termos independentes**, as constantes.

Para solucionar o sistema linear abaixo, precisamos encontrar os valores das variáveis **x1** e **x2**:  
![Exemplo Sistemas Lineares](exsistemalinear.jpg) 

In [73]:
A = np.array(([-1,2],[2,1]))
B = np.array(([-1],[5]))

In [74]:
#Se a determinante de A for diferente de zero, significa que ela possui uma matriz inversa correspondente
if np.linalg.det(A) != 0:
    X = inv(A).dot(B)

In [75]:
X

array([[2.2],
       [0.6]])

É possível resolver sistema de equações lineares de forma mais rápida e eficiente através do método **solve()** da biblioteca Numpy.

In [76]:
X = np.linalg.solve(A,B)
X

array([[2.2],
       [0.6]])

### Determinantes de Matrizes
Para explicar o que são determinantes de matrizes, iremos analisar o sistema de equações lineares abaixo:  
![Exemplo 1 Sistemas Lineares](ex1sistemalinear.jpg) 

Estamos à procura das incógnitas do sistema, x1 e x2. Para isso devemos isolar uma das variáveis e substituir na outra equação, ao final do processo iremos chegar em duas equações:  
![x1](x1.jpg)  
![x2](x2.jpg)

Podemos notar que o denominador das equações x1 e x2 são os mesmos. Essas constantes que aparecem no denominador das matrizes são chamadas de **determinantes** de uma matriz. **O determinante só pode ser calculado em uma matriz quadrada.**

### Calculando o determinante  
* A determinante de uma matriz 1x1, ou seja, de um escalar é o próprio escalar
* A determinante de uma matriz 2x2 é a multiplicação dos elementos da diagonal principal subtraído pela multiplicação dos elementos da diagonal secundária
* Para uma matriz 3x3, pode ser utilizado o **método de Sarrus**, exemplificado abaixo:  
![Método de Sarrus](sarrus.jpg)  

Podemos utilizar outros teoremas para encontrarmos a determinante de uma matriz, como por exemplo o **teorema de Laplace, decomposição LU, eliminação gaussiana** dentre outros.

A linguagem Python nos permite encontrar determinantes de matrizes de forma prática através da função **det()**.

In [77]:
from numpy.linalg import det

In [78]:
A = np.array(([1,2,4],[5,3,-1],[7,2,0]))
det_A = det(A)
det_A

-56.00000000000002

In [79]:
B = np.array(([1,2,4,5,6,7],
              [5,3,-1,5,1,2],
              [7,2,0,1,4,9],
              [1,2,1,5,6,5],
              [-7,2,4,-1,6,6],
              [0,2,5,5,9,7]))
B

array([[ 1,  2,  4,  5,  6,  7],
       [ 5,  3, -1,  5,  1,  2],
       [ 7,  2,  0,  1,  4,  9],
       [ 1,  2,  1,  5,  6,  5],
       [-7,  2,  4, -1,  6,  6],
       [ 0,  2,  5,  5,  9,  7]])

In [80]:
det(B)

8184.000000000006

## Transformação Linear  
Uma Transformação Linear é um tipo especial de função entre dois espaços vetorias, associando um vetor a outro e preservando as propriedades de adição vetorial e multiplicação por escalar. 
![Transformação U->V](transformação1.jpg) 

Para uma transformação ser considerada linear, a seguinte propriedade deve ser satisfeita: 
![Propriedades Transformação Linear](propriedadetransformaçãolinear.jpg)


Após essa breve explicação de transformação linear podemos introduzir o conceito de autovalores e autovetores.


### Autovalores e autovetores  
Considerando a transformação linear de um espaço vetorial:
![Transformação V->V](transformação2.jpg)  
Os **autovetores(v)** são as direções que foram preservadas após a transformação. Enquanto os **autovalores(λ)**, são os escalares que multiplicam o vetor v. Lembrando que **v!=0**.

![Autovalor e Autovetor](autovalorvetor.jpg) 



Podemos obter os autovalores e os autovetores correspondentes através do método **numpy.linalg.eig**

In [81]:
import numpy.linalg as al

In [82]:
A = np.array(([4,2,0],[-1,1,0],[0,1,2]))
autovalores, autovetores = al.eig(A)

In [83]:
autovalores

array([2., 2., 3.])

In [84]:
autovetores

array([[ 0.00000000e+00,  4.44089210e-16, -8.16496581e-01],
       [ 0.00000000e+00, -4.44089210e-16,  4.08248290e-01],
       [ 1.00000000e+00,  1.00000000e+00,  4.08248290e-01]])

# Aplicação
## Algoritmo de ranqueamento do Google  
Ao realizarmos uma busca no Google, é retornado as páginas ordenadas por relevância. Mas como é definida a relevância de uma página?  
![Page Rank](google.jpg) 

Desenvolvido por Larry Page e Sergey Brin em 1995, o algoritmo PageRank contabiliza a importância de uma página de acordo com a quantidade de links que direcionam para ela. A quantidade não é a única variável responsável por definir a importância de uma página, para uma página ser considerada relevante, a mesma deve ser apontada por diversas outras páginas consideradas relevantes.  

E o que os conceitos apresentados anteriormente tem a ver com o ranqueamento de páginas do Google? **TUDO!**  

O método utilizado pelos criadores do Google no desenvolvimento do algoritmo foi proposto por **Kendall e Wei** na década de 1950. A hipótese do modelo é que a importância de um site é proporcional à importância dos sites que apontam para ele. Considere Xi, 1 <= i <= n, a importância do i-ésimo site.  Representando utilizando um sistema de equações, temos que:  
![Sistema de Equações PageRank](equaçoespagerank.jpg) 

A constante K relaciona à importância dos sites que apontam para x1,x2,...,xn. Todo o sistema pode ser representado pela seguinte equação:
![Equação PageRank](equaçãopagerank.jpg)  

A matriz A é conhecida como **matriz de transição** e possuí duas propriedades: 
1. **todas as entradas são não-negativas**
2. **a soma das entradas de todas as colunas são iguais a 1**  

De acordo com o **Teorema de Perron-Frobenius**, seja A uma matriz de transição, λ=1 é um autovalor de A. Os autovetores associado ao autovalor 1/k determinam a importância dos sites, sua maior coordenada refere-se ao site mais importante, a segunda ao segundo site mais relevante e assim sucessivamente.


Com Numpy, após encontrarmos os autovalores com o método **numpy.linalg.eig()** podemos fazer o ordenamento e obter o site de maior relevância com o método **numpy.argsort()**.

In [ ]:
A = np.array(([0,0.5,0.5,0.5,1,0],
              [0,0,0,0,0,0],
              [0,0,0,0,0,0],
              [0,0.5,0.5,0,0,1],
              [1,0,0,0,0,0],
              [0,0,0,0.5,0,0]))
w, v = al.eig(A)
ind = np.agrsort(w)[::-1]
w_dec = w[ind]
v_dec = v[ind]

## Referências
[Ebook Álgebra Linear com Python: Aprenda na prática os principais conceitos](https://www.amazon.com.br/%C3%81lgebra-Linear-com-Python-principais-ebook/dp/B07FNWM2P8)  
Utilizado como principal referência para o desenvolvimento deste notebook. Apresenta brevemente os principais conceitos de álgebra linear, de maneira superficial fazendo o uso do pacote NumPy.
![ebook](capalivro.jpg) 

Com o objetivo de complementar o estudo, foram utilizados os materiais abaixo:  
[Transformações Lineares](https://www.ufrgs.br/reamat/AlgebraLinear/livro/s3-transformax00e7x00f5es_lineares.html)  
[Autovalores e Autovetores de uma matriz](https://www.respondeai.com.br/workspace/topico/52/1063/teoria/1026)
[Aplicações de Autovalores e Autovetores](https://www.ime.usp.br/mat/2458/textos/eigenvalues.pdf)     
[Introdução a cadeias de Markov](https://www.ime.usp.br/~mbranco/Aulacadeiamarko_MAE03992017.pdf)  
[Autovalores e autovetores: utilização na classificação de relevância](https://periodicos.ufsm.br/cienciaenatura/article/download/35529/19193)  
[Um pouco da matemática por trás do algoritmo de PageRank do Google](https://repositorio.ufsc.br/xmlui/bitstream/handle/123456789/160733/337665.pdf?sequence=1&isAllowed=y)  
